---@type LazySpec
return {
  -- use biome as default formatter now, see ./biome.lua
  { import = "plugins.coding.formatting" },
  -- {
  --   "williamboman/mason.nvim",
  --   opts = function(_, opts)
  --     table.insert(opts.ensure_installed, "prettierd")
  --   end,
  -- },
  -- {
  --   "stevearc/conform.nvim",
  --   opts = {
  --     formatters_by_ft = {
  --       -- Web
  --       ["javascript"] = { "prettierd" },
  --       ["javascriptreact"] = { "prettierd" },
  --       ["typescript"] = { "prettierd" },
  --       ["typescriptreact"] = { "prettierd" },
  --       ["vue"] = { "prettierd" },
  --       ["css"] = { "prettierd" },
  --       ["scss"] = { "prettierd" },
  --       ["less"] = { "prettierd" },
  --       ["html"] = { "prettierd" },
  --       ["json"] = { "prettierd" },
  --       ["jsonc"] = { "prettierd" },
  --       ["yaml"] = { "prettierd" },
  --       ["markdown"] = { "prettierd" },
  --       ["markdown.mdx"] = { "prettierd" },
  --       ["graphql"] = { "prettierd" },
  --       ["handlebars"] = { "prettierd" },
  --     },
  --   },
  -- },
}
